---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tos
description: Fedora Kionite with my personal tweaks and modifications.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg/repo/fedora-%OS_VERSION%/whitehara-kernel-tkg-fedora-%OS_VERSION%.repo
    install:
      - gamemode
    remove:
      - firefox
      - firefox-langpacks
      - plasma-welcome-fedora
      - plasma-welcome
      - krfb
      - krfb-libs
      - ublue-os-update-services
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/whitehara/kernel-tkg/repo/fedora-%OS_VERSION%/whitehara-kernel-tkg-fedora-%OS_VERSION%.repo
        packages:
          - kernel
          - kernel-core
          - kernel-modules
          - kernel-devel

  - type: default-flatpaks
    system:
      install:
        - com.brave.Browser
      remove:
        - org.mozilla.Firefox
        - org.mozilla.Thunderbird
        - io.github.flattool.Warehouse

  - type: signing
